auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Lippi's home
url: http://lippiouyangonline.info
feed: /atom.xml
author_info: <a href="http://LippiOuYangonline.info/">LippiOuYang</a>
